global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'rate-limiter'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['rate-limiter:8080']
    
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] 