apiVersion: v1
kind: Secret
metadata:
  name: rate-limiter-secrets
  labels:
    app: rate-limiter
type: Opaque
stringData:
  # Placeholder secrets (replace with actual values in a secure way)
  redis-password: ""
  jwt-secret: "replace-with-secure-random-token"
  api-keys: "admin-key:admin,read-key:readonly,write-key:user"
  basic-auth-username: "admin"
  basic-auth-password: "replace-with-secure-password"
---
apiVersion: v1
kind: Secret
metadata:
  name: rate-limiter-tls
  labels:
    app: rate-limiter
type: kubernetes.io/tls
data:
  # Placeholder for TLS certificates (base64 encoded)
  # Generate using:
  # openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout server.key -out server.crt
  tls.crt: ""  # Add base64 encoded certificate
  tls.key: ""  # Add base64 encoded private key 