apiVersion: v1
kind: ServiceAccount
metadata:
  name: rate-limiter
  labels:
    app: rate-limiter
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rate-limiter-role
  labels:
    app: rate-limiter
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rate-limiter-rolebinding
  labels:
    app: rate-limiter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rate-limiter-role
subjects:
- kind: ServiceAccount
  name: rate-limiter
  namespace: default 